"""HMARL maritime MVP package."""

from .agents import FleetCoordinatorAgent, PortAgent, VesselAgent, assign_vessels_to_coordinators
from .analysis import (
    compare_to_baselines,
    compute_ablation_deltas,
    compute_training_stats,
    format_comparison_table,
    rank_sweep_results,
    summarize_experiment,
)
from .buffer import MultiAgentRolloutBuffer, RolloutBuffer
from .checkpointing import EarlyStopping, TrainingCheckpoint
from .config import (
    DISTANCE_NM,
    SEED,
    DecisionCadence,
    HMARLConfig,
    generate_distance_matrix,
    get_default_config,
    resolve_distance_matrix,
    should_update,
    validate_config,
)
from .curriculum import (
    CurriculumScheduler,
    CurriculumStage,
    make_curriculum_configs,
)
from .dynamics import compute_fuel_and_emissions, dispatch_vessel, step_ports, step_vessels
from .env import MaritimeEnv
from .experiment import (
    run_experiment,
    run_horizon_sweep,
    run_mappo_ablation,
    run_mappo_comparison,
    run_mappo_hyperparam_sweep,
    run_multi_seed,
    run_multi_seed_mappo_comparison,
    run_multi_seed_policy_sweep,
    run_noise_sweep,
    run_policy_sweep,
    run_sharing_sweep,
    save_result_dict,
    summarize_multi_seed,
    summarize_policy_results,
)
from .forecasts import MediumTermForecaster, OracleForecaster, ShortTermForecaster
from .learned_forecaster import (
    ForecastDataset,
    LearnedForecaster,
    TrainResult,
    build_forecast_dataset,
    collect_queue_traces,
    train_forecaster,
)
from .logger import TrainingLogger
from .mappo import (
    MAPPOConfig,
    MAPPOTrainer,
    ObsRunningMeanStd,
    PPOUpdateResult,
    RunningMeanStd,
    global_state_dim_from_config,
)
from .message_bus import MessageBus
from .metrics import (
    compute_economic_metrics,
    compute_economic_step_deltas,
    compute_port_metrics,
    compute_vessel_metrics,
    forecast_mae,
    forecast_rmse,
)
from .networks import (
    ActorCritic,
    ContinuousActor,
    Critic,
    DiscreteActor,
    apply_orthogonal_init,
    build_actor_critics,
    obs_dim_from_env,
)
from .plotting import (
    plot_ablation_bar,
    plot_horizon_sweep,
    plot_mappo_comparison,
    plot_noise_sweep,
    plot_policy_comparison,
    plot_sharing_sweep,
    plot_sweep_heatmap,
    plot_training_curves,
    plot_training_dashboard,
)
from .policies import FleetCoordinatorPolicy, PortPolicy, VesselPolicy
from .report import (
    generate_ablation_report,
    generate_sweep_report,
    generate_training_report,
)
from .rewards import (
    compute_coordinator_reward_step,
    compute_port_reward,
    compute_vessel_reward_step,
)
from .state import PortState, VesselState, initialize_ports, initialize_vessels, make_rng

__all__ = [
    "ActorCritic",
    "ContinuousActor",
    "Critic",
    "CurriculumScheduler",
    "CurriculumStage",
    "DISTANCE_NM",
    "DecisionCadence",
    "DiscreteActor",
    "EarlyStopping",
    "FleetCoordinatorAgent",
    "FleetCoordinatorPolicy",
    "ForecastDataset",
    "HMARLConfig",
    "LearnedForecaster",
    "MAPPOConfig",
    "MAPPOTrainer",
    "MaritimeEnv",
    "MediumTermForecaster",
    "MessageBus",
    "MultiAgentRolloutBuffer",
    "ObsRunningMeanStd",
    "OracleForecaster",
    "PPOUpdateResult",
    "PortAgent",
    "PortPolicy",
    "PortState",
    "RolloutBuffer",
    "RunningMeanStd",
    "SEED",
    "ShortTermForecaster",
    "TrainResult",
    "TrainingCheckpoint",
    "TrainingLogger",
    "VesselAgent",
    "VesselPolicy",
    "VesselState",
    "apply_orthogonal_init",
    "assign_vessels_to_coordinators",
    "build_actor_critics",
    "build_forecast_dataset",
    "collect_queue_traces",
    "compare_to_baselines",
    "compute_ablation_deltas",
    "compute_coordinator_reward_step",
    "compute_economic_metrics",
    "compute_economic_step_deltas",
    "compute_port_metrics",
    "compute_port_reward",
    "compute_training_stats",
    "compute_vessel_metrics",
    "compute_fuel_and_emissions",
    "compute_vessel_reward_step",
    "dispatch_vessel",
    "forecast_mae",
    "forecast_rmse",
    "format_comparison_table",
    "generate_ablation_report",
    "generate_distance_matrix",
    "get_default_config",
    "generate_sweep_report",
    "generate_training_report",
    "global_state_dim_from_config",
    "initialize_ports",
    "initialize_vessels",
    "make_curriculum_configs",
    "make_rng",
    "obs_dim_from_env",
    "plot_ablation_bar",
    "plot_horizon_sweep",
    "plot_mappo_comparison",
    "plot_noise_sweep",
    "plot_policy_comparison",
    "plot_sharing_sweep",
    "plot_sweep_heatmap",
    "plot_training_curves",
    "plot_training_dashboard",
    "rank_sweep_results",
    "resolve_distance_matrix",
    "run_experiment",
    "run_horizon_sweep",
    "run_mappo_ablation",
    "run_mappo_comparison",
    "run_mappo_hyperparam_sweep",
    "run_multi_seed",
    "run_multi_seed_mappo_comparison",
    "run_multi_seed_policy_sweep",
    "run_noise_sweep",
    "run_policy_sweep",
    "run_sharing_sweep",
    "save_result_dict",
    "should_update",
    "step_ports",
    "step_vessels",
    "summarize_experiment",
    "summarize_multi_seed",
    "summarize_policy_results",
    "train_forecaster",
    "validate_config",
]
